<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\UserLog;

class UserLogController extends Controller
{
    /**
     * =========================================================
     * 📋 USER / ADMIN LOGS
     * =========================================================
     *
     * Displays the audit log while applying:
     *
     * - Role-based access control
     * - Action filtering
     * - Date filtering
     * - Search
     * - Sorting
     * - Pagination
     *
     * The controller also prepares a reliable target label
     * for the logs table.
     */
    public function index(Request $request)
    {
        /**
         * =====================================================
         * 🔒 SORT
         * =====================================================
         *
         * Only ASC and DESC are accepted.
         *
         * This is a whitelist rather than directly trusting
         * user input.
         */
        $sort = $request->get('sort', 'desc');

        $sort = in_array(
            $sort,
            ['asc', 'desc'],
            true
        )
            ? $sort
            : 'desc';


        /**
         * =====================================================
         * 🔥 ADMIN ACTIONS
         * =====================================================
         *
         * This list is the source of truth for actions that
         * belong to administrators.
         *
         * Keep this synchronized with the action names used
         * by the controllers that create UserLog records.
         */
        $adminActions = [

            // Authentication
            'admin_login',
            'admin_logout',

            // Agency management
            'create_agency',
            'update_agency',
            'trash_agency',
            'restore_agency',
            'force_delete_agency',

            // Legacy agency action.
            // Kept temporarily so older records remain
            // classified correctly.
            'delete_agency',

            // FAQ management
            'create_faq',
            'update_faq',
            'delete_faq',

            // Admin management
            'approve_admin',
            'invite_admin',
            'promote_admin',
            'demote_admin',
            'delete_admin',
        ];


        /**
         * =====================================================
         * 🔧 BASE QUERY
         * =====================================================
         *
         * Eager loading prevents N+1 database queries when
         * the Blade accesses the actor, agency, or target user.
         *
         * The Agency relationship already uses withTrashed()
         * in UserLog, so soft-deleted agencies remain
         * resolvable here.
         */
        $query = UserLog::with([
                'agency',
                'user',
                'targetUser',
            ])
            ->orderBy(
                'created_at',
                $sort
            );


        /**
         * =====================================================
         * 🔐 ROLE-BASED DATA ACCESS
         * =====================================================
         */
        $user = auth()->user();


        /*
         * A regular administrator:
         *
         * 1. Can see their own logs.
         *
         * 2. Can see logs generated by normal users.
         *
         * 3. Cannot see other administrator/superadmin logs.
         *
         * 4. Cannot see administrator-management actions from
         *    normal-user records.
         */
        if ($user->role === 'admin') {

            $query->where(function ($q) use (
                $user,
                $adminActions
            ) {

                /*
                 * Own logs.
                 */
                $q->where(
                    'user_id',
                    $user->id
                )

                /*
                 * Normal-user logs.
                 */
                ->orWhere(function ($sub) use (
                    $adminActions
                ) {

                    $sub->whereHas(
                        'user',
                        function ($userQuery) {

                            $userQuery->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                });
            });
        }


        /**
         * =====================================================
         * 📌 BASE QUERY SNAPSHOT
         * =====================================================
         *
         * This is used later for generating available filter
         * options without accidentally including filters that
         * should not be available to the current user.
         */
        $baseQuery = clone $query;


        /**
         * =====================================================
         * 🔍 FILTER: ROLE
         * =====================================================
         */
        if ($request->role === 'admin') {

            $query->whereHas(
                'user',
                function ($q) {

                    $q->whereIn(
                        'role',
                        [
                            'admin',
                            'superadmin',
                        ]
                    );
                }
            );
        }


        if ($request->role === 'user') {

            $query->whereHas(
                'user',
                function ($q) {

                    $q->where(
                        'role',
                        'user'
                    );
                }
            );
        }


        /**
         * =====================================================
         * 🔍 FILTER: ACTION
         * =====================================================
         */
        if ($request->filled('action')) {

            $query->where(
                'action',
                $request->action
            );
        }


        /**
         * =====================================================
         * 📅 FILTER: DATE
         * =====================================================
         */
        if ($request->filled('date')) {

            $query->whereDate(
                'created_at',
                $request->date
            );
        }


        /**
         * =====================================================
         * 🔎 SEARCH
         * =====================================================
         *
         * Search supports:
         *
         * - Action
         * - Page
         * - Actor first name
         * - Actor last name
         * - Existing agency name
         * - Stored audit snapshots
         *
         * The old_values fallback is important for permanently
         * deleted agencies because their actual database row
         * no longer exists.
         */
        if ($request->filled('search')) {

            $search = trim(
                $request->search
            );


            $query->where(function ($q) use ($search) {

                /*
                 * Action.
                 */
                $q->where(
                    'action',
                    'LIKE',
                    "%{$search}%"
                )


                /*
                 * Page.
                 */
                ->orWhere(
                    'page',
                    'LIKE',
                    "%{$search}%"
                )


                /*
                 * Actor name.
                 */
                ->orWhereHas(
                    'user',
                    function ($userQuery) use ($search) {

                        $userQuery
                            ->where(
                                'first_name',
                                'LIKE',
                                "%{$search}%"
                            )
                            ->orWhere(
                                'last_name',
                                'LIKE',
                                "%{$search}%"
                            );
                    }
                )


                /*
                 * Existing agency records.
                 */
                ->orWhereHas(
                    'agency',
                    function ($agencyQuery) use ($search) {

                        $agencyQuery->where(
                            'agency_name',
                            'LIKE',
                            "%{$search}%"
                        );
                    }
                )


                /*
                 * Historical agency information.
                 *
                 * This is particularly useful for
                 * force_delete_agency logs.
                 */
                ->orWhere(
                    'old_values',
                    'LIKE',
                    "%{$search}%"
                )


                /*
                 * Also search new_values because some actions
                 * may store relevant information there.
                 */
                ->orWhere(
                    'new_values',
                    'LIKE',
                    "%{$search}%"
                );
            });
        }


        /**
         * =====================================================
         * 🔧 AVAILABLE ACTIONS
         * =====================================================
         *
         * Build the action dropdown from the same access
         * restrictions as the logs themselves.
         */
        $availableActions = (clone $baseQuery)

            ->when(
                $request->role === 'admin',
                function ($q) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->whereIn(
                                'role',
                                [
                                    'admin',
                                    'superadmin',
                                ]
                            );
                        }
                    );
                }
            )

            ->when(
                $request->role === 'user',
                function ($q) use ($adminActions) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                }
            )

            ->select('action')

            ->distinct()

            ->orderBy('action')

            ->pluck('action');


        /**
         * =====================================================
         * 📄 PAGINATION
         * =====================================================
         */
        $logs = $query
            ->paginate(10)
            ->withQueryString();


        /**
         * =====================================================
         * 🎯 PREPARE LOG TARGETS
         * =====================================================
         *
         * This is the important new part.
         *
         * The Blade should eventually use:
         *
         *     $log->log_target
         *
         * instead of trying to determine the target itself.
         *
         * Normal agency logs:
         *
         *     agency relationship → agency name
         *
         * Permanently deleted agency:
         *
         *     old_values['agency_name']
         *
         * User-related logs:
         *
         *     targetUser relationship
         *
         * System-only logs:
         *
         *     System
         */
        $logs->getCollection()->transform(
            function ($log) {

                /*
                 * =================================================
                 * AGENCY TARGET
                 * =================================================
                 *
                 * If the agency still exists or is soft-deleted,
                 * UserLog::agency can resolve it.
                 */
                if ($log->agency) {

                    $log->log_target =
                        'Agency #' .
                        $log->agency->id;


                    /*
                     * Store the readable agency name separately.
                     *
                     * The Blade can choose which presentation
                     * it prefers.
                     */
                    $log->log_target_name =
                        $log->agency->agency_name;

                    return $log;
                }


                /*
                 * =================================================
                 * PERMANENTLY DELETED AGENCY
                 * =================================================
                 *
                 * The actual agency row no longer exists.
                 *
                 * However, our audit log preserved the agency
                 * name in old_values before forceDelete().
                 */
                if (
                    $log->agency_id &&
                    is_array($log->old_values) &&
                    !empty(
                        $log->old_values['agency_name']
                    )
                ) {

                    $log->log_target =
                        'Agency #' .
                        $log->agency_id;

                    $log->log_target_name =
                        $log->old_values[
                            'agency_name'
                        ];

                    return $log;
                }


                /*
                 * =================================================
                 * TARGET USER
                 * =================================================
                 *
                 * Used by actions such as admin management.
                 */
                if ($log->targetUser) {

                    $log->log_target =
                        'User #' .
                        $log->targetUser->id;

                    $log->log_target_name =
                        trim(
                            $log->targetUser->first_name .
                            ' ' .
                            $log->targetUser->last_name
                        );

                    return $log;
                }


                /*
                 * =================================================
                 * FALLBACK
                 * =================================================
                 *
                 * This should only be used when the action truly
                 * has no entity target.
                 *
                 * Examples:
                 *
                 *     admin_login
                 *     admin_logout
                 *     navigate
                 */
                $log->log_target =
                    'System';

                $log->log_target_name =
                    'System';


                return $log;
            }
        );


        /**
         * =====================================================
         * 📊 STATISTICS
         * =====================================================
         */
        $totalLogs =
            UserLog::count();

        $totalNavigation =
            UserLog::where(
                'action',
                'navigate'
            )->count();

        $totalAgencyViews =
            UserLog::where(
                'action',
                'view_agency'
            )->count();


        /**
         * =====================================================
         * 📅 AVAILABLE DATES
         * =====================================================
         *
         * Generate dates using the same visibility rules as
         * the logs available to the current user.
         */
        $availableDates = (clone $baseQuery)

            ->when(
                $request->role === 'admin',
                function ($q) use ($user) {

                    if ($user->role === 'admin') {

                        /*
                         * Regular admins can only select dates
                         * containing their own logs.
                         */
                        $q->where(
                            'user_id',
                            $user->id
                        );

                    } else {

                        /*
                         * Superadmins can see admin logs.
                         */
                        $q->whereHas(
                            'user',
                            function ($u) {

                                $u->whereIn(
                                    'role',
                                    [
                                        'admin',
                                        'superadmin',
                                    ]
                                );
                            }
                        );
                    }
                }
            )

            ->when(
                $request->role === 'user',
                function ($q) use ($adminActions) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                }
            )

            ->selectRaw(
                'DATE(created_at) as date'
            )

            ->distinct()

            ->orderBy(
                'date',
                'desc'
            )

            ->limit(15)

            ->pluck('date');


        /**
         * =====================================================
         * 🚀 RETURN VIEW
         * =====================================================
         */
        return view(
            'admin.logs',
            compact(
                'logs',
                'availableDates',
                'availableActions',
                'totalLogs',
                'totalNavigation',
                'totalAgencyViews'
            )
        );
    }
}