<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\UserLog;

class UserLogController extends Controller
{
    /**
     * =========================================================
     * 📋 USER / ADMIN LOGS
     * =========================================================
     *
     * Displays the audit log while applying:
     *
     * - Role-based access control
     * - Action filtering
     * - Date filtering
     * - Search
     * - Sorting
     * - Pagination
     *
     * The controller also prepares a reliable target label
     * for every audit record.
     */
    public function index(Request $request)
    {
        /**
         * =====================================================
         * 🔒 SORT
         * =====================================================
         *
         * Only ASC and DESC are accepted.
         *
         * This is a whitelist rather than directly trusting
         * user input.
         */
        $sort = $request->get('sort', 'desc');

        $sort = in_array(
            $sort,
            ['asc', 'desc'],
            true
        )
            ? $sort
            : 'desc';


        /**
         * =====================================================
         * 🔥 ADMIN ACTIONS
         * =====================================================
         *
         * This list identifies actions generated by
         * administrators.
         *
         * Keep this synchronized with the action names used
         * throughout the administrative controllers.
         */
        $adminActions = [

            /*
             * Authentication
             */
            'admin_login',
            'admin_logout',

            /*
             * Agency management
             */
            'create_agency',
            'update_agency',
            'trash_agency',
            'restore_agency',
            'force_delete_agency',

            /*
             * Legacy agency action.
             */
            'delete_agency',

            /*
             * FAQ management
             */
            'create_faq',
            'update_faq',
            'delete_faq',
            'restore_faq',
            'force_delete_faq',

            /*
             * Category management
             */
            'create_category',
            'update_category',
            'delete_category',
            'restore_category',
            'force_delete_category',

            /*
            * Support Request management
            */
            'delete_support_request',
            'restore_support_request',
            'force_delete_support_request',

            /*
            * Administrator management
            */
            'approve_admin',
            'invite_admin',
            'promote_admin',
            'demote_admin',
            'deactivate_admin',
            'reactivate_admin',
            'delete_admin',

            /*
            * Public User Management
            */
            'deactivate_user',
            'reactivate_user',
            'delete_user',
        ];


        /**
         * =====================================================
         * 🔧 BASE QUERY
         * =====================================================
         *
         * Eager-load relationships used by the logs page.
         *
         * Agency and Category relationships use withTrashed()
         * so soft-deleted records remain resolvable.
         */
        $query = UserLog::with([
            'agency',
            'category',
            'supportRequest',
            'user',
            'targetUser',
        ])
            ->orderBy(
                'created_at',
                $sort
            );


        /**
         * =====================================================
         * 🔐 CURRENT USER
         * =====================================================
         */
        $user = auth()->user();


        /**
         * =====================================================
         * 🔐 ROLE-BASED DATA ACCESS
         * =====================================================
         *
         * Regular administrators:
         *
         * - Can see their own logs.
         * - Can see normal-user activity.
         * - Cannot see other administrator logs.
         * - Cannot see administrative actions generated by
         *   normal-user records.
         *
         * Superadmins are not restricted by this block.
         */
        if ($user->role === 'admin') {

            $query->where(function ($q) use (
                $user,
                $adminActions
            ) {

                /*
                 * Own logs.
                 */
                $q->where(
                    'user_id',
                    $user->id
                )

                /*
                 * Normal-user logs.
                 */
                ->orWhere(function ($sub) use (
                    $adminActions
                ) {

                    $sub->whereHas(
                        'user',
                        function ($userQuery) {

                            $userQuery->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                });
            });
        }


        /**
         * =====================================================
         * 📌 AUTHORIZED QUERY SNAPSHOT
         * =====================================================
         *
         * Everything derived from this query follows the same
         * visibility rules as the main logs table.
         */
        $baseQuery = clone $query;


        /**
         * =====================================================
         * 🔍 FILTER: ROLE
         * =====================================================
         */
        if ($request->role === 'admin') {

            $query->whereHas(
                'user',
                function ($q) {

                    $q->whereIn(
                        'role',
                        [
                            'admin',
                            'superadmin',
                        ]
                    );
                }
            );
        }


        if ($request->role === 'user') {

            $query->whereHas(
                'user',
                function ($q) {

                    $q->where(
                        'role',
                        'user'
                    );
                }
            );
        }


        /**
         * =====================================================
         * 🔍 FILTER: ACTION
         * =====================================================
         */
        if ($request->filled('action')) {

            $query->where(
                'action',
                $request->action
            );
        }


        /**
         * =====================================================
         * 📅 FILTER: DATE
         * =====================================================
         */
        if ($request->filled('date')) {

            $query->whereDate(
                'created_at',
                $request->date
            );
        }


        /**
         * =====================================================
         * 🔎 SEARCH
         * =====================================================
         *
         * Search supports:
         *
         * - Action
         * - Page
         * - Actor name
         * - Existing agency name
         * - Existing category name
         * - Historical old_values
         * - Historical new_values
         */
        if ($request->filled('search')) {

            $search = trim(
                $request->search
            );


            $query->where(function ($q) use ($search) {

                /*
                 * Action.
                 */
                $q->where(
                    'action',
                    'LIKE',
                    "%{$search}%"
                )


                /*
                 * Page.
                 */
                ->orWhere(
                    'page',
                    'LIKE',
                    "%{$search}%"
                )


                /*
                 * Actor name.
                 */
                ->orWhereHas(
                    'user',
                    function ($userQuery) use ($search) {

                        $userQuery
                            ->where(
                                'first_name',
                                'LIKE',
                                "%{$search}%"
                            )
                            ->orWhere(
                                'last_name',
                                'LIKE',
                                "%{$search}%"
                            );
                    }
                )


                /*
                 * Existing agency records.
                 */
                ->orWhereHas(
                    'agency',
                    function ($agencyQuery) use ($search) {

                        $agencyQuery->where(
                            'agency_name',
                            'LIKE',
                            "%{$search}%"
                        );
                    }
                )

                /*
 * Existing Support Request records.
 */
->orWhereHas(
    'supportRequest',
    function ($supportQuery) use ($search) {

        $supportQuery->where(
            'question',
            'LIKE',
            "%{$search}%"
        );
    }
)


                /*
                 * Existing category records.
                 */
                ->orWhereHas(
                    'category',
                    function ($categoryQuery) use ($search) {

                        $categoryQuery->where(
                            'category_name',
                            'LIKE',
                            "%{$search}%"
                        );
                    }
                )


                /*
                 * Historical audit information.
                 *
                 * This remains searchable even after the
                 * related record has been permanently deleted.
                 */
                ->orWhere(
                    'old_values',
                    'LIKE',
                    "%{$search}%"
                )


                ->orWhere(
                    'new_values',
                    'LIKE',
                    "%{$search}%"
                );
            });
        }


        /**
         * =====================================================
         * 🔧 AVAILABLE ACTIONS
         * =====================================================
         *
         * Build the action dropdown using the same visibility
         * restrictions as the logs themselves.
         */
        $availableActions = (clone $baseQuery)

            ->when(
                $request->role === 'admin',
                function ($q) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->whereIn(
                                'role',
                                [
                                    'admin',
                                    'superadmin',
                                ]
                            );
                        }
                    );
                }
            )

            ->when(
                $request->role === 'user',
                function ($q) use ($adminActions) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                }
            )

            ->reorder()

->select('action')

->distinct()

->orderBy('action')

->pluck('action');


        /**
         * =====================================================
         * 📅 AVAILABLE DATES
         * =====================================================
         *
         * Dates are generated from the authorized base query
         * so filter options never expose unauthorized records.
         */
        $availableDates = (clone $baseQuery)

            ->when(
                $request->role === 'admin',
                function ($q) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->whereIn(
                                'role',
                                [
                                    'admin',
                                    'superadmin',
                                ]
                            );
                        }
                    );
                }
            )

            ->when(
                $request->role === 'user',
                function ($q) use ($adminActions) {

                    $q->whereHas(
                        'user',
                        function ($u) {

                            $u->where(
                                'role',
                                'user'
                            );
                        }
                    )

                    ->whereNotIn(
                        'action',
                        $adminActions
                    );
                }
            )

            ->reorder()

->selectRaw(
    'DATE(created_at) as date'
)

->distinct()

->orderBy(
    'date',
    'desc'
)

->limit(15)

->pluck('date');


        /**
         * =====================================================
         * 📄 PAGINATION
         * =====================================================
         */
        $logs = $query
            ->paginate(10)
            ->withQueryString();


        /**
         * =====================================================
         * 🎯 PREPARE LOG TARGETS
         * =====================================================
         *
         * IMPORTANT:
         *
         * Audit target resolution is based on the foreign-key
         * stored inside the audit record.
         *
         * The existence of the related database record only
         * determines where we obtain its display name.
         *
         * This is important because an audit log must remain
         * meaningful even after the target is permanently deleted.
         *
         * Resolution priority:
         *
         * 1. category_id
         * 2. agency_id
         * 3. target_user_id
         * 4. System
         *
         * For deleted entities:
         *
         * old_values/new_values become the historical source
         * of the display name.
         */
        $logs->getCollection()->transform(
            function ($log) {

                /**
                 * =================================================
                 * CATEGORY TARGET
                 * =================================================
                 *
                 * We check category_id FIRST.
                 *
                 * This is intentional.
                 *
                 * The audit record itself tells us that the
                 * affected entity is a category.
                 *
                 * We must not depend on the Category model still
                 * existing.
                 */
                if ($log->category_id) {

                    /*
                     * The category still exists or is soft-deleted.
                     *
                     * The relationship uses withTrashed(), so
                     * soft-deleted categories can still be resolved.
                     */
                    if ($log->category) {

                        $log->log_target =
                            'Category #' .
                            $log->category->id;

                        $log->log_target_name =
                            $log->category->category_name;

                        return $log;
                    }


                    /*
                     * The category was permanently deleted.
                     *
                     * Recover the historical name from the
                     * audit snapshots.
                     *
                     * old_values is preferred because destructive
                     * category actions store the previous state there.
                     *
                     * new_values is also checked for creation/update
                     * records and older audit formats.
                     */
                    $categoryName =
                        $log->old_values['category_name']
                        ?? $log->new_values['category_name']
                        ?? 'Deleted Category';


                    $log->log_target =
                        'Category #' .
                        $log->category_id;

                    $log->log_target_name =
                        $categoryName;

                    return $log;
                }

                /**
 * =================================================
 * SUPPORT REQUEST TARGET
 * =================================================
 *
 * Support Request logs have their own foreign key.
 *
 * The relationship uses withTrashed(), so a soft-deleted
 * request can still be resolved.
 *
 * If the request was permanently deleted, the relationship
 * returns null. The audit snapshot remains available as the
 * historical source of truth.
 */
if ($log->support_request_id) {

    /*
     * Existing or soft-deleted Support Request.
     */
    if ($log->supportRequest) {

        $log->log_target =
            'Support Request #' .
            $log->supportRequest->id;

        $log->log_target_name =
            'Support Request #' .
            $log->supportRequest->id;

        return $log;
    }


    /*
     * Permanently deleted Support Request.
     *
     * The actual database row no longer exists, but the
     * audit snapshot still contains its original ID.
     */
    $supportRequestId =
        $log->old_values['support_request_id']
        ?? $log->new_values['support_request_id']
        ?? $log->support_request_id;


    $log->log_target =
        'Support Request #' .
        $supportRequestId;

    $log->log_target_name =
        'Support Request #' .
        $supportRequestId;

    return $log;
}


                /**
                 * =================================================
                 * AGENCY TARGET
                 * =================================================
                 *
                 * The same principle applies to agencies.
                 *
                 * agency_id tells us that the audit record belongs
                 * to an agency even if the agency itself has already
                 * been permanently deleted.
                 */
                if ($log->agency_id) {

                    /*
                     * Existing or soft-deleted agency.
                     */
                    if ($log->agency) {

                        $log->log_target =
                            'Agency #' .
                            $log->agency->id;

                        $log->log_target_name =
                            $log->agency->agency_name;

                        return $log;
                    }


                    /*
                     * Permanently deleted agency.
                     *
                     * Recover the historical name from the audit
                     * snapshot.
                     */
                    $agencyName =
                        $log->old_values['agency_name']
                        ?? $log->new_values['agency_name']
                        ?? 'Deleted Agency';


                    $log->log_target =
                        'Agency #' .
                        $log->agency_id;

                    $log->log_target_name =
                        $agencyName;

                    return $log;
                }


                /**
 * =================================================
 * TARGET USER
 * =================================================
 *
 * Used by administrator/user-management actions.
 *
 * If the target account still exists, use its current
 * information.
 *
 * If the target account was permanently deleted,
 * target_user_id and the audit snapshot remain available.
 */
if ($log->target_user_id) {

    /*
     * Target account still exists.
     */
    if ($log->targetUser) {

        $log->log_target =
            'User #' .
            $log->targetUser->id;

        $log->log_target_name =
            trim(
                $log->targetUser->first_name .
                ' ' .
                $log->targetUser->last_name
            );

        return $log;
    }


    /*
     * Target account was permanently deleted.
     *
     * The User relationship is no longer available,
     * so use the historical audit snapshot.
     */
    $firstName =
        $log->old_values['first_name']
        ?? '';

    $lastName =
        $log->old_values['last_name']
        ?? '';

    $historicalName =
        trim(
            $firstName .
            ' ' .
            $lastName
        );


    /*
     * If a historical name was stored, display it.
     */
    if ($historicalName !== '') {

        $log->log_target =
            'User #' .
            $log->target_user_id;

        $log->log_target_name =
            $historicalName;

        return $log;
    }


    /*
     * Name was not available in the snapshot.
     *
     * Email is a useful historical fallback.
     */
    if (
        !empty(
            $log->old_values['email']
        )
    ) {

        $log->log_target =
            'User #' .
            $log->target_user_id;

        $log->log_target_name =
            $log->old_values['email'];

        return $log;
    }

    /*
 * =========================================================
 * CROSS-LOG HISTORICAL FALLBACK
 * =========================================================
 *
 * Older user-management logs may only contain the changed
 * status and therefore have no first_name/last_name snapshot.
 *
 * If the target user was later permanently deleted, another
 * audit record for the same target_user_id may still contain
 * the user's historical identity.
 */
$historicalIdentity =
    UserLog::where(
        'target_user_id',
        $log->target_user_id
    )

    /*
     * Prefer records that actually contain a historical
     * first name, last name, or email.
     */
    ->where(function ($query) {

        $query
            ->where(
                'old_values',
                'LIKE',
                '%"first_name"%'
            )

            ->orWhere(
                'old_values',
                'LIKE',
                '%"last_name"%'
            )

            ->orWhere(
                'old_values',
                'LIKE',
                '%"email"%'
            );
    })

    /*
     * The newest matching audit snapshot is the most
     * relevant historical identity.
     */
    ->latest('created_at')

    ->first();


if ($historicalIdentity) {

    $historicalValues =
        $historicalIdentity->old_values ?? [];


    if (is_array($historicalValues)) {

        $historicalFirstName =
            $historicalValues['first_name'] ?? '';

        $historicalLastName =
            $historicalValues['last_name'] ?? '';

        $historicalName =
            trim(
                $historicalFirstName .
                ' ' .
                $historicalLastName
            );


        if ($historicalName !== '') {

            $log->log_target =
                'User #' .
                $log->target_user_id;

            $log->log_target_name =
                $historicalName;

            return $log;
        }


        if (
            !empty(
                $historicalValues['email']
            )
        ) {

            $log->log_target =
                'User #' .
                $log->target_user_id;

            $log->log_target_name =
                $historicalValues['email'];

            return $log;
        }
    }
}


    /*
     * We know a user was targeted, but no historical
     * identifying information was stored.
     */
    $log->log_target =
        'User #' .
        $log->target_user_id;

    $log->log_target_name =
        'Deleted User';

    return $log;
}


                /**
                 * =================================================
                 * SYSTEM FALLBACK
                 * =================================================
                 *
                 * Only genuine targetless actions should reach
                 * this point.
                 *
                 * Examples:
                 *
                 * - admin_login
                 * - admin_logout
                 * - navigate
                 */
                $log->log_target =
                    'System';

                $log->log_target_name =
                    'System';

                return $log;
            }
        );


        /**
         * =====================================================
         * 📊 STATISTICS
         * =====================================================
         *
         * Statistics use the same authorized query scope as
         * the logs page.
         */
        $statisticsQuery = clone $baseQuery;


        $totalLogs =
            (clone $statisticsQuery)->count();


        $totalNavigation =
            (clone $statisticsQuery)
                ->where(
                    'action',
                    'navigate'
                )
                ->count();


        $totalAgencyViews =
            (clone $statisticsQuery)
                ->where(
                    'action',
                    'view_agency'
                )
                ->count();


        /**
         * =====================================================
         * 🚀 RETURN VIEW
         * =====================================================
         */
        return view(
            'admin.logs',
            compact(
                'logs',
                'availableDates',
                'availableActions',
                'totalLogs',
                'totalNavigation',
                'totalAgencyViews'
            )
        );
    }
}